### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by maarek** [riferrei/srclient#21]
It seems that there is a breaking change in the Schema Registry API posted by Confluent. Older APIs do not allow `schemaType` to be in the payload of a POST request to create a schema. Since these APIs do not support unknown fields, what are possible solutions to handle those who want to use the `srclient` with older schema registries.

I am leaving this open for ideas on how best to tackle compatibility while progressing the client as Confluent updates the API.

Ref. #11 #19

**Comment by alok87** [comment]
I am using `confluentinc/cp-schema-registry:5.0.1` docker image for schema registry. Since you have reverted #12 it would start breaking for everyone using 5.0.1. 

Helm still has the default as 5.0.1.

**Comment by chrisdginn** [comment]
This definitely works with 5.5.1.  Since Avro is the default in 5.5.1, why not just make a change that only sends the schema type if it's not Avro.  While it's a temporary solution until there is a better workaround, it would at least achieve backwards compatibility without a major amount of work.   Otherwise it's going to require some kind of compatibility flag. Unfortunately, the Schema Registry API doesn't look like it has an operation to get the version of the schema registry you are connecting to, nor does it provide that information in any of the headers.

https://docs.confluent.io/current/schema-registry/develop/api.html#

**Comment by AtakanColak** [comment]
I'm closing this issue to inactivity, seems like schemaType is not present in POST requests anymore, so should support old versions anyways. If not, then hopefully upcoming CI I'm planning to work on should show us that.
