### ISSUE TITLE
Schema Registry retry and check if the schema exist

### ISSUE THREAD

**Issue by alok87** [riferrei/srclient#42]
```go
func (c *cSchemaRegistry) GetLatestSchema(
	subject string, key bool) (*Schema, error) {
	cSchema, err := c.client.GetLatestSchema(subject, key)
	if err != nil {
		return nil, err
	}

	return toSchema(cSchema), nil
}
```

This call returns the error in both the cases:
1. when the schema does not exist, it returns the error
2. when their was a network issue in making the call, it returns the error.

I want to add a retry mechanism only for the 2nd case. How do I check if the error was for 1 and not 2?

**Comment by AtakanColak** [comment]
I think you should use `func (client *SchemaRegistryClient) GetSubjects() ([]string, error)` and iterate over subjects to check if a subject(schema) exists. Because if this returns and error, there is an issue with the network or the schema registry. Otherwise you could always use `errors.Is(err, target)` to check if the error is a network error.

**Comment by alok87** [comment]
how to distinguish between network and not found error? Are the errors returned have exported type? Can you please point to the code..

**Comment by AtakanColak** [comment]
Can't because errors are dynamically created at [createError](https://github.com/riferrei/srclient/blob/7be54965ba084e38873753d4faac0d4c1aad4540/schemaRegistryClient.go#L515). You should reproduce your errors in unit tests and then use `errors.Is`. Again I think you should use subject list to check if a schema exists.

**Comment by alok87** [comment]
cool thanks
